### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Lykos153** [Lykos153/AnnexRemote#1]

**Comment by rkdarst** [comment]
Hi,

Thanks for AnnexRemote!  I've just created a remote based on it, https://github.com/rkdarst/git-annex-remote-irods (who knows how serious it will become.  The Python version is in the irods2 file).

I was mostly able to create the basic remote.  I wasn't entirely sure how to make the ExportRemote version, because I wasn't sure how to handle the arguments.  I could suggest an easy, and good-enough-for-most-cases, method would be re-implementing the example found here: https://git-annex.branchable.com/special_remotes/external/ using AnnexRemote.  It was very simple and allowed me to easily adapt all commands to my own remote.  I think having this would be *almost* as good as proper documentation for most users.

I may have more comments on AnnexRemote later, but for now I think my biggest problems are iRODS itself...

**Comment by Lykos153** [comment]
Thanks a lot for your feedback! I just updated the README and tried to make the naming of the arguments clearer. Re-implementing the example is a very good idea, indeed.
